before_commands:
     - composer self-update
     - composer install --dev
     - pecl install channel://pecl.php.net/libevent-0.1.0
tools:
    php_code_coverage:
        filter:
            paths: [ 'src' ]
    php_code_sniffer:
        config:
            standard: PSR1
    php_cs_fixer: true
    php_mess_detector: true
    php_analyzer:
        filter:
            excluded_paths: [ 'tests' ]
    sensiolabs_security_checker: true
