language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - composer install
  - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit --configuration tests/phpunit.xml --coverage-text